### ISSUE TITLE
Get duration of message

### ISSUE THREAD

**Issue by mattbk** [markfickett/arduinomorse#13]
Is there a way to get the duration of the message being sent (how many ms it takes to send)? 

In the reference example below, it would be useful to get back the duration of the `cqSender` message with something like `ms = cqSender.duration();`

From the examples:
```
#include <morse.h>

#define PIN_STATUS	13

void setup()
{
	LEDMorseSender cqSender(PIN_STATUS);
	cqSender.setup();
	cqSender.setMessage(String("cq "));
	cqSender.sendBlocking();
}

void loop()
{
}
```

**Comment by markfickett** [comment]
That would certainly be possible, especially since the `sendBlocking` method is currently `void`. I could see either just recording before/after times and subtracting to return that, or calculating the expected duration from the `timingBuffer`. I haven't touched this in years though so I don't have the implementation at my fingertips; probably up to you or someone else who comes along to contribute. Thanks for using the library!

**Comment by mattbk** [comment]
Thanks for the reply. I figured out a way around it using `millis()`.
